General:
  FasttextDirectory: ./fasttext
  MatrixDirectory: ./processed_embs
FasttextLink:
    url: https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/
    prefix: wiki
    suffix: align.vec
AvailabeLangs:
    Afrikaans: af
    Arabic: ar
    Bulgarian: bg
    Bengali: bn
    Bosnian: bs
    Catalan: ca
    Czech: cz
    Danish: da
    German: de
    Greek: el
    English: en
    Spanish: es
    Estonian: et
    Persian: fa
    Finnish: fi
    French: fr
    Hebrew: he
    Hindi: hi
    Croatian: hr
    Hungarian: hu
    Indonesian: id
    Italian: it
    Korean: ko
    Lithuanian: lt
    Latvian: lv
    Macedonian: mk
    Malay: ms
    Dutch: nl
    Norwegian: no
    Polish: pl
    Portuguese: pt
    Romanian: ro
    Russian: ru
    Slovak: sk
    Slovenian: sl
    Albanian: sq
    Swedish: sv
    Tamil: ta
    Thai: th
    Tagalog: tl
    Turkish: tr
    Ukrainian: uk
    Vietnamese: vi
    Chinese: zh